name: Run Herald Bluesky Bot

on:
  schedule:
    - cron: '0,30 * * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 python-dotenv pytz lxml playwright atproto
          python -m playwright install --with-deps

      - name: Run Herald Bluesky Bot
        env:
          BLUESKY_HANDLE: ${{ secrets.BLUESKY_HANDLE }}
          BLUESKY_APP_PASSWORD: ${{ secrets.BLUESKY_APP_PASSWORD }}
        run: python herald_bluesky_bot.py

      - name: Commit posted URLs
        env:
          TOKEN: ${{ secrets.ACTIONS_PAT }}
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add posted_urls_bluesky.txt || echo "No files to add"
          git commit -m "Update posted_urls_bluesky.txt [skip ci]" || echo "No changes to commit"
          git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }} || echo "Nothing to push"
