name: Run Herald Twitter Bot

on:
  schedule:
    - cron: '15,45 * * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies (including Playwright)
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 tweepy python-dotenv pytz lxml playwright
          python -m playwright install --with-deps

      - name: Run Herald Twitter Bot
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
        run: python herald_bot.py

      - name: Commit posted URLs
        env:
          TOKEN: ${{ secrets.ACTIONS_PAT }}
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          touch posted_urls_twitter.txt
          git add posted_urls_twitter.txt || echo "No files to add"
          git commit -m "Update posted_urls_twitter.txt [skip ci]" || echo "No changes to commit"
          git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }} || echo "Nothing to push"
